zhebera/practicum-android-diploma

app/build.gradle.kts

Настройка build.gradle-файла
(minSdk == 26 в файле /gradle/libs.versions.toml)

fix #6 Настройка build.gradle-файлов 

---

app/src/main/AndroidManifest.xml
app/src/main/java/ru/practicum/android/diploma/App.kt

fix #4 epic0 task 4 androidmanifest.xml

---

app/src/main/AndroidManifest.xml

windowSoftInputMode добавлен
(Может имеет смысл добавить еще свойство windowSoftInputMode для того, чтобы в последующей работе была возможность скрывать клавиатуру программно?)

fix #4 дополнение: epic0 task4 androidmanifest.xml

---

app/src/main/java/ru/practicum/android/diploma/App.kt
app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt

Добавлены модули, подключен koin в файле App

Fix #17 задачи - DI

---

app/src/main/java/ru/practicum/android/diploma/ui/root/RootActivity.kt
app/src/main/res/layout/activity_root.xml

Fix #1 Изменены RootActivity и activity_root.xml

Fix #1 Изменены RootActivity и activity_root.xml

---

app/src/main/java/ru/practicum/android/diploma/data/dto/Response.kt
app/src/main/java/ru/practicum/android/diploma/data/network/NetworkClient.kt
app/src/main/java/ru/practicum/android/diploma/data/network/Response.kt
app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
app/src/main/res/color/bottom_navigation_color.xml
app/src/main/res/layout/activity_root.xml
app/src/main/res/values/strings.xml

1. Удалены файлы заглушки в подпапках, где уже есть файлы, относящиеся к проекту
2. Изменена строка создателей приложения
3. перенесем файл класна Response в пакет dto
4. добавлены параметры для отображения актуального цвета в BottomNavigationView

Последние изменения перед сдачей PR

---

app/src/main/java/ru/practicum/android/diploma/data/db/dao/VacancyDao.kt
app/src/main/java/ru/practicum/android/diploma/data/favourite/FavouriteRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/favourite/FavouriteInteractor.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/favourite/FavouriteRepository.kt
app/src/main/java/ru/practicum/android/diploma/domain/impl/FavouriteInteractorImpl.kt
app/src/main/java/ru/practicum/android/diploma/ui/details/fragment/VacancyDescriptionFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/details/viewmodel/VacancyDescriptionViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/favourite/fragment/FavouriteFragment.kt
app/src/main/java/ru/practicum/android/diploma/util/Consts.kt
app/src/main/res/navigation/navigation_graph.xml

Epic3 task34 favourite button listeners

---

app/src/main/res/layout/fragment_filter_industry.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

close #77 создан layout для выбора отрасли

---

app/src/main/java/ru/practicum/android/diploma/ui/regions/fragment/RegionsWorkPlaceFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/workplace/fragment/FilterWorkPlaceFragment.kt
app/src/main/res/layout/fragment_filter_region.xml
app/src/main/res/navigation/navigation_graph.xml

close #82 реализация перехода на экран выбора региона работы

---

app/src/main/java/ru/practicum/android/diploma/ui/filter/fragment/FilterFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/industry/fragment/FilterIndustryFragment.kt
app/src/main/res/layout/fragment_filter_industry.xml
app/src/main/res/navigation/navigation_graph.xml

close #84 ерализация перехода на экран выбора отрасли

---

app/src/main/java/ru/practicum/android/diploma/ui/countries/fragment/CountriesWorkPlaceFragment.kt
app/src/main/res/layout/fragment_filter_country.xml

Fix #93 Добавлена логика перехода назад с экрана "Страны" на экран "Место работы"

Fix #93 Добавлена логика перехода назад с экрана "Страны" на экран "Место работы"

---

app/src/main/java/ru/practicum/android/diploma/ui/regions/fragment/RegionsWorkPlaceFragment.kt

Fix #94 Добавлена логика перехода назад с экрана "Регионы" на экран "Место работы"

Fix #94 Добавлена логика перехода назад с экрана "Регионы" на экран "Место работы"

---

app/src/main/java/ru/practicum/android/diploma/data/countries/CountriesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/countries/CountriesInteractor.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/countries/CountriesRepository.kt
app/src/main/java/ru/practicum/android/diploma/domain/impl/countries/CountriesInteractorImpl.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/Country.kt

Epic5 task97 api countries

---

app/src/main/java/ru/practicum/android/diploma/data/converters/CountriesConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/countries/CountriesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/data/network/HeadHunterApi.kt
app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
app/src/main/java/ru/practicum/android/diploma/data/request/CountriesRequest.kt
app/src/main/java/ru/practicum/android/diploma/data/response/CountriesResponse.kt
app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/countries/CountriesInteractor.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/countries/CountriesRepository.kt
app/src/main/java/ru/practicum/android/diploma/domain/impl/countries/CountriesInteractorImpl.kt

Epic5 task100 countries repository impl

---

app/src/main/java/ru/practicum/android/diploma/data/regions/RegionsRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/regions/RegionsInteractor.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/regions/RegionsRepository.kt
app/src/main/java/ru/practicum/android/diploma/domain/impl/regions/RegionsInteractorImpl.kt

Fix #105 - интерекатор и репозиторий для получений регионов

---

app/src/main/java/ru/practicum/android/diploma/data/countries/CountriesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
app/src/main/java/ru/practicum/android/diploma/ui/countries/adapter/CountriesAdapter.kt
app/src/main/java/ru/practicum/android/diploma/ui/countries/adapter/CountriesViewHolder.kt
app/src/main/java/ru/practicum/android/diploma/ui/countries/fragment/CountriesWorkPlaceFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/countries/viewmodel/CountriesState.kt
app/src/main/java/ru/practicum/android/diploma/ui/countries/viewmodel/CountriesViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/workplace/fragment/FilterWorkPlaceFragment.kt

Epic5 task110 UI viewmodel countries

---

app/src/main/java/ru/practicum/android/diploma/data/sharedpreferences/SharedPreferencesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/sharedpreferences/SharedPreferencesInteractor.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/sharedpreferences/SharedPreferencesRepository.kt
app/src/main/java/ru/practicum/android/diploma/domain/impl/sharedpreferences/SharedPreferencesInteractorImpl.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/FilterModel.kt
app/src/main/java/ru/practicum/android/diploma/util/Consts.kt

Fix #123 - Shared Preferences API

Fix #123 - Shared Preferences API

---

app/src/main/java/ru/practicum/android/diploma/domain/models/Industry.kt
app/src/main/java/ru/practicum/android/diploma/ui/filter/fragment/FilterFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/industry/fragment/FilterIndustryFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/industry/viewmodel/FilterIndustryViewModel.kt
app/src/main/java/ru/practicum/android/diploma/util/Consts.kt

close #134 get industry to filter fragment

---

app/src/main/java/ru/practicum/android/diploma/ui/filter/fragment/FilterFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/workplace/fragment/FilterWorkPlaceFragment.kt

close #138 add button listener

---

app/src/main/java/ru/practicum/android/diploma/data/sharedpreferences/SharedPreferencesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/sharedpreferences/SharedPreferencesInteractor.kt
app/src/main/java/ru/practicum/android/diploma/domain/api/sharedpreferences/SharedPreferencesRepository.kt
app/src/main/java/ru/practicum/android/diploma/domain/impl/sharedpreferences/SharedPreferencesInteractorImpl.kt

Fix #135 - Shared prefs исправления

---

app/src/main/java/ru/practicum/android/diploma/ui/filter/fragment/FilterFragment.kt

Fix #140 - Определение логики нажатия иконок Места работы и Отрасли на экране Фильтр

---

app/src/main/java/ru/practicum/android/diploma/data/regions/RegionsRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt

Сортировка регионов (исключение стран), вытаскивание вложенных регионов и добавление их в список выдачи

Epic5 task148 edit regions repository

---

app/src/main/java/ru/practicum/android/diploma/data/network/HeadHunterApi.kt
app/src/main/java/ru/practicum/android/diploma/data/regions/RegionsRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/Region.kt
app/src/main/java/ru/practicum/android/diploma/ui/regions/adapter/RegionsAdapter.kt
app/src/main/java/ru/practicum/android/diploma/ui/regions/adapter/RegionsViewHolder.kt
app/src/main/java/ru/practicum/android/diploma/ui/regions/fragment/RegionsWorkPlaceFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/regions/viewmodel/RegionsViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/workplace/fragment/FilterWorkPlaceFragment.kt
app/src/main/res/layout/fragment_filter_region.xml

Реализовано отображение данных на экране RegionsFragment и нажатие на Region

Epic5 task106 regions fragment show data

---

app/src/main/java/ru/practicum/android/diploma/data/sharedpreferences/SharedPreferencesRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/FilterModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/filter/fragment/FilterFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/filter/viewmodel/FilterViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/regions/fragment/RegionsWorkPlaceFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/search/viewmodel/SearchViewModel.kt
app/src/main/java/ru/practicum/android/diploma/ui/workplace/fragment/FilterWorkPlaceFragment.kt

Fix #158 - Исправление поведения экрана Фильтр 

---

app/src/main/java/ru/practicum/android/diploma/data/converters/CountriesConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/network/HeadHunterApi.kt
app/src/main/java/ru/practicum/android/diploma/data/response/CountriesResponse.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/Country.kt

Fix #160 - исправление запроса для поиска стран

---

app/src/main/java/ru/practicum/android/diploma/data/converters/RegionsConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/regions/RegionsRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/Region.kt
app/src/main/java/ru/practicum/android/diploma/ui/workplace/fragment/FilterWorkPlaceFragment.kt

Fix #164 - отображение страны при выборе региона

---

app/src/main/java/ru/practicum/android/diploma/data/favourite/FavouriteRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/ui/search/viewmodel/SearchViewModel.kt

Epic6 task170 change map for searching

---

app/src/main/res/layout/card_sector.xml
app/src/main/res/layout/fragment_filter_industry.xml

close #174 change industry ui

---

app/src/main/java/ru/practicum/android/diploma/ui/search/adapter/VacancyAdapter.kt
app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/SearchFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/search/viewmodel/SearchState.kt
app/src/main/java/ru/practicum/android/diploma/ui/search/viewmodel/SearchViewModel.kt
app/src/main/java/ru/practicum/android/diploma/util/Consts.kt
app/src/main/res/layout/fragment_search.xml

close #180 add search pagination

---

app/src/main/java/ru/practicum/android/diploma/data/converters/db/keyskills/KeySkillDbConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/converters/db/keyskills/KeySkillEntityConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/converters/db/keyskills/ListKeySkillDbConverter.kt
app/src/main/java/ru/practicum/android/diploma/data/db/entity/VacancyDescriptionEntity.kt
app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDescription.kt
app/src/main/java/ru/practicum/android/diploma/ui/details/fragment/VacancyDescriptionFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/favourite/fragment/FavouriteFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/SearchFragment.kt
app/src/main/java/ru/practicum/android/diploma/ui/search/viewmodel/SearchState.kt
app/src/main/java/ru/practicum/android/diploma/ui/search/viewmodel/SearchViewModel.kt
app/src/main/res/values/strings.xml

close #186 fix some bugs
